/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Nowis 3D (https://sketchfab.com/Nowis3D)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kamisama-no-shinden-b6dbdf5e61c845d5925d5dd653c493cb
Title: Kamisama no Shinden
*/

import { useEffect, useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from "@react-three/fiber";

import KamisamaPlanetScene from "@/assets/3d/kamisamaPlanet.glb";

import { a } from "@react-spring/three";
import { GLTFResult } from "./types";

export function KamisamaPlanet(props: JSX.IntrinsicElements["group"]) {
  const planetRef = useRef(null);
  const { nodes, materials } = useGLTF(KamisamaPlanetScene) as GLTFResult;
  return (
    <a.group {...props} ref={planetRef}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="Root">
            <group
              name="Icosphere"
              position={[0, 0, 1]}
              scale={[1, 1, 0.77044]}
            >
              <mesh
                name="Icosphere_1"
                geometry={nodes.Icosphere_1.geometry}
                material={materials["Material.002"]}
              />
              <mesh
                name="Icosphere_2"
                geometry={nodes.Icosphere_2.geometry}
                material={materials["Material.013"]}
              />
            </group>
            <group name="Icosphere001" position={[0, 0, 1]}>
              <mesh
                name="Icosphere001_1"
                geometry={nodes.Icosphere001_1.geometry}
                material={materials["Material.001"]}
              />
            </group>
            <group
              name="Cylinder"
              position={[-0.5667, 0.17673, 1.29974]}
              scale={[0.01306, 0.01306, 0.26725]}
            >
              <mesh
                name="Cylinder_1"
                geometry={nodes.Cylinder_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Sphere"
              position={[-0.56679, 0.17673, 1.61985]}
              scale={[0.09288, 0.09288, 0.06195]}
            >
              <mesh
                name="Sphere_1"
                geometry={nodes.Sphere_1.geometry}
                material={materials["Material.015"]}
              />
              <mesh
                name="Sphere_2"
                geometry={nodes.Sphere_2.geometry}
                material={materials["Material.012"]}
              />
            </group>
            <group
              name="Sphere001"
              position={[-0.37239, 0.56555, 1.61985]}
              scale={[0.09288, 0.09288, 0.06195]}
            >
              <mesh
                name="Sphere001_1"
                geometry={nodes.Sphere001_1.geometry}
                material={materials["Material.015"]}
              />
              <mesh
                name="Sphere001_2"
                geometry={nodes.Sphere001_2.geometry}
                material={materials["Material.012"]}
              />
            </group>
            <group
              name="Cylinder001"
              position={[-0.37229, 0.56555, 1.29974]}
              scale={[0.01306, 0.01306, 0.26725]}
            >
              <mesh
                name="Cylinder001_1"
                geometry={nodes.Cylinder001_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Cylinder002"
              position={[0.37265, 0.56555, 1.29974]}
              scale={[-0.01306, 0.01306, 0.26725]}
            >
              <mesh
                name="Cylinder002_1"
                geometry={nodes.Cylinder002_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Sphere002"
              position={[0.37275, 0.56555, 1.61985]}
              scale={[-0.09288, 0.09288, 0.06195]}
            >
              <mesh
                name="Sphere002_1"
                geometry={nodes.Sphere002_1.geometry}
                material={materials["Material.015"]}
              />
              <mesh
                name="Sphere002_2"
                geometry={nodes.Sphere002_2.geometry}
                material={materials["Material.012"]}
              />
            </group>
            <group
              name="Sphere003"
              position={[0.56716, 0.17673, 1.61985]}
              scale={[-0.09288, 0.09288, 0.06195]}
            >
              <mesh
                name="Sphere003_1"
                geometry={nodes.Sphere003_1.geometry}
                material={materials["Material.014"]}
              />
              <mesh
                name="Sphere003_2"
                geometry={nodes.Sphere003_2.geometry}
                material={materials["Material.012"]}
              />
            </group>
            <group
              name="Cylinder003"
              position={[0.56706, 0.17673, 1.29974]}
              scale={[-0.01306, 0.01306, 0.26725]}
            >
              <mesh
                name="Cylinder003_1"
                geometry={nodes.Cylinder003_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group name="Icosphere002" position={[0, 0, 1.11118]}>
              <mesh
                name="Icosphere002_1"
                geometry={nodes.Icosphere002_1.geometry}
                material={materials["Material.003"]}
              />
              <mesh
                name="Icosphere002_2"
                geometry={nodes.Icosphere002_2.geometry}
                material={materials["Material.006"]}
              />
            </group>
            <group
              name="Cylinder004"
              position={[0, 0, -0.37996]}
              scale={[0.05184, 0.05184, 0.61591]}
            >
              <mesh
                name="Cylinder004_1"
                geometry={nodes.Cylinder004_1.geometry}
                material={materials["Material.005"]}
              />
            </group>
            <group
              name="Cube"
              position={[0, 0.19637, 1.04452]}
              scale={[0.33133, 0.12744, 0.00622]}
            >
              <mesh
                name="Cube_1"
                geometry={nodes.Cube_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Sphere004"
              position={[0, 0.17919, 1.35099]}
              scale={0.07778}
            >
              <mesh
                name="Sphere004_1"
                geometry={nodes.Sphere004_1.geometry}
                material={materials["Material.011"]}
              />
              <mesh
                name="Sphere004_2"
                geometry={nodes.Sphere004_2.geometry}
                material={materials["Material.010"]}
              />
              <mesh
                name="Sphere004_3"
                geometry={nodes.Sphere004_3.geometry}
                material={materials["Material.012"]}
              />
            </group>
            <group
              name="Cylinder005"
              position={[0, -0.11434, 1.17647]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.06539, 0.03664, 0.11849]}
            >
              <mesh
                name="Cylinder005_1"
                geometry={nodes.Cylinder005_1.geometry}
                material={materials["Material.010"]}
              />
              <mesh
                name="Cylinder005_2"
                geometry={nodes.Cylinder005_2.geometry}
                material={materials["Material.012"]}
              />
            </group>
            <group
              name="Cylinder006"
              position={[-0.29524, 0.18005, 1.17647]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={[0.06539, 0.03664, 0.11849]}
            >
              <mesh
                name="Cylinder006_1"
                geometry={nodes.Cylinder006_1.geometry}
                material={materials["Material.012"]}
              />
              <mesh
                name="Cylinder006_2"
                geometry={nodes.Cylinder006_2.geometry}
                material={materials["Material.010"]}
              />
            </group>
            <group
              name="Cylinder007"
              position={[0.29763, 0.18005, 1.17647]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.06539, 0.03664, 0.11849]}
            >
              <mesh
                name="Cylinder007_1"
                geometry={nodes.Cylinder007_1.geometry}
                material={materials["Material.012"]}
              />
              <mesh
                name="Cylinder007_2"
                geometry={nodes.Cylinder007_2.geometry}
                material={materials["Material.010"]}
              />
            </group>
            <group
              name="Sphere005"
              position={[0.21274, 0.46965, 1.33258]}
              scale={0.05511}
            >
              <mesh
                name="Sphere005_1"
                geometry={nodes.Sphere005_1.geometry}
                material={materials["Material.009"]}
              />
              <mesh
                name="Sphere005_2"
                geometry={nodes.Sphere005_2.geometry}
                material={materials["Material.010"]}
              />
              <mesh
                name="Sphere005_3"
                geometry={nodes.Sphere005_3.geometry}
                material={materials["Material.012"]}
              />
            </group>
            <group
              name="Sphere006"
              position={[-0.21354, 0.46965, 1.33258]}
              scale={0.05511}
            >
              <mesh
                name="Sphere006_1"
                geometry={nodes.Sphere006_1.geometry}
                material={materials["Material.009"]}
              />
              <mesh
                name="Sphere006_2"
                geometry={nodes.Sphere006_2.geometry}
                material={materials["Material.010"]}
              />
              <mesh
                name="Sphere006_3"
                geometry={nodes.Sphere006_3.geometry}
                material={materials["Material.012"]}
              />
            </group>
            <group
              name="Plane"
              position={[0, -0.00164, 1.13373]}
              rotation={[Math.PI / 2, 0, 0]}
              scale={[0.07735, 0.09738, 0.05606]}
            >
              <mesh
                name="Plane_1"
                geometry={nodes.Plane_1.geometry}
                material={materials["Material.007"]}
              />
            </group>
            <group
              name="Plane001"
              position={[-0.18194, 0.17924, 1.13373]}
              rotation={[Math.PI / 2, -Math.PI / 2, 0]}
              scale={[0.07735, 0.09738, 0.05606]}
            >
              <mesh
                name="Plane001_1"
                geometry={nodes.Plane001_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Plane002"
              position={[0.18384, 0.17924, 1.13373]}
              rotation={[Math.PI / 2, Math.PI / 2, 0]}
              scale={[0.07735, 0.09738, 0.05606]}
            >
              <mesh
                name="Plane002_1"
                geometry={nodes.Plane002_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group name="Plane003" scale={[0.11736, 0.03152, 0.03152]}>
              <mesh
                name="Plane003_1"
                geometry={nodes.Plane003_1.geometry}
                material={materials["Material.003"]}
              />
              <mesh
                name="Plane003_2"
                geometry={nodes.Plane003_2.geometry}
                material={materials["Material.008"]}
              />
            </group>
            <group name="Cube001" position={[0, 0, 2.73391]} scale={0.00277}>
              <mesh
                name="Cube001_1"
                geometry={nodes.Cube001_1.geometry}
                material={materials.Material}
              />
            </group>
            <group name="Plane004" position={[0, 0, 4.17959]} scale={0.03113}>
              <mesh
                name="Plane004_1"
                geometry={nodes.Plane004_1.geometry}
                material={materials["Material.004"]}
              />
            </group>
            <group
              name="Cube002"
              position={[0, 0, 1.11421]}
              scale={[0.00377, 0.00377, 0.06348]}
            >
              <mesh
                name="Cube002_1"
                geometry={nodes.Cube002_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Icosphere003"
              position={[0, 0, -0.4295]}
              scale={[1, 1, 0.151]}
            >
              <mesh
                name="Icosphere003_1"
                geometry={nodes.Icosphere003_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Icosphere004"
              position={[-1.11949, 0, -0.11999]}
              rotation={[0, 0, -Math.PI]}
              scale={[0.30842, 0.30842, 0.08093]}
            >
              <mesh
                name="Icosphere004_1"
                geometry={nodes.Icosphere004_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Icosphere005"
              position={[0.77359, 0.34582, 0.19252]}
              rotation={[-2.96707, 0, -Math.PI]}
              scale={[0.30842, 0.30842, 0.08093]}
            >
              <mesh
                name="Icosphere005_1"
                geometry={nodes.Icosphere005_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Icosphere006"
              position={[-0.0934, -0.62145, 0.12214]}
              rotation={[-Math.PI, 0, Math.PI / 2]}
              scale={[0.19582, 0.60752, 0.08093]}
            >
              <mesh
                name="Icosphere006_1"
                geometry={nodes.Icosphere006_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Icosphere007"
              position={[0.80126, -0.92904, -0.06034]}
              rotation={[-0.00001, 0.17453, -1.57079]}
              scale={[0.19324, 0.47054, 0.08258]}
            >
              <mesh
                name="Icosphere007_1"
                geometry={nodes.Icosphere007_1.geometry}
                material={materials["Icosphere.007"]}
              />
            </group>
            <group
              name="Icosphere008"
              position={[0, 0.17934, 1.49151]}
              scale={0.01437}
            >
              <mesh
                name="Icosphere008_1"
                geometry={nodes.Icosphere008_1.geometry}
                material={materials["Material.010"]}
              />
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
}

export default KamisamaPlanet;
